plugins {
    id 'java'
}

group = 'com.tenco'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}


dependencies {

    // 커넥션 풀 LIB
    implementation group: 'com.zaxxer', name: 'HikariCP', version: '5.1.0'

    // SLF4J
    implementation group: 'org.slf4j', name: 'slf4j-api', version: '2.0.17'
    implementation group: 'org.slf4j', name: 'slf4j-simple', version: '2.0.17'

    // MySQL
    implementation group: 'com.mysql', name: 'mysql-connector-j', version: '8.4.0'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    testCompileOnly 'org.projectlombok:lombok:1.18.46'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'

    implementation 'org.mindrot:jbcrypt:0.4'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
